ACTIVATION_FOOTPRINT_FACTOR = 12
COST_CONTROLLER = 0.19

BYTES_FP16 = 2
BYTES_FP32 = 4
MEMORY_BUCKET_DEEPSPEED_SIZE = 500000000  # 5*e8 model parameters 'MEMORY_OPT_ALLREDUCE_SIZE' in DeepSpeed
# LLM
NUM_KEY_VALUE_HEADS = 4
MLP_GATED_LINEAR_UNITS = False
SHARED_EMBEDDING = True
EMBEDDING_LAYER = "embed2h"
TRANSFORMER_LAYER = "transformer_layer"
LAST_LAYERNORM = "embed2v"

# OPTIMIZATION
GPU_NAMES = ['V100', 'A100', 'A100-40', 'A100-80', 'T4', 'P100', 'G2']

# TODO: check if these are needed
DEFAULT_MAX_COST = 1000000
DEFAULT_MIN_THROUGHPUT_PERCENTAGE = 0.1
